import XCTest
@testable import MiriCore

final class ClaudeSessionDiscoveryTests: XCTestCase {
    private var root: URL!

    override func setUpWithError() throws {
        root = FileManager.default.temporaryDirectory
            .appending(path: "claude-discovery-\(UUID().uuidString)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: root)
    }

    @discardableResult
    private func writeTranscript(
        project: String,
        session: String,
        lines: [String],
        subdirectory: String? = nil
    ) throws -> URL {
        var directory = root.appending(path: project, directoryHint: .isDirectory)
        if let subdirectory {
            directory = directory.appending(path: subdirectory, directoryHint: .isDirectory)
        }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appending(path: "\(session).jsonl")
        try lines.joined(separator: "\n").appending("\n").write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private func userLine(_ text: String, cwd: String? = nil) -> String {
        var object: [String: Any] = ["type": "user", "message": ["role": "user", "content": text]]
        if let cwd { object["cwd"] = cwd }
        return String(decoding: try! JSONSerialization.data(withJSONObject: object), as: UTF8.self)
    }

    func testDiscoversSessionsWithTitleAndProject() throws {
        try writeTranscript(
            project: "-Users-someone-Developer-miri",
            session: "aaaa1111-2222-3333-4444-555566667777",
            lines: [
                #"{"type":"mode","mode":"normal"}"#,
                userLine("refactor the delivery coordinator", cwd: "/Users/someone/Developer/miri"),
            ]
        )

        let sessions = ClaudeSessionDiscovery.sessions(in: root)
        XCTAssertEqual(sessions.count, 1)
        XCTAssertEqual(sessions.first?.agent, .claude)
        XCTAssertEqual(sessions.first?.title, "refactor the delivery coordinator")
        XCTAssertEqual(sessions.first?.workingDirectory, "/Users/someone/Developer/miri")
        XCTAssertEqual(sessions.first?.projectName, "miri")
    }

    /// The directory name replaces "/" with "-", so a project whose own name
    /// contains a hyphen cannot be recovered from it. The transcript's `cwd`
    /// is authoritative and must win.
    func testWorkingDirectoryComesFromTranscriptNotTheLossyDirectoryName() throws {
        try writeTranscript(
            project: "-Users-someone-Developer-dhanpat-vps",
            session: "bbbb1111-2222-3333-4444-555566667777",
            lines: [userLine("deploy it", cwd: "/Users/someone/Developer/dhanpat-vps")]
        )

        let sessions = ClaudeSessionDiscovery.sessions(in: root)
        XCTAssertEqual(sessions.first?.projectName, "dhanpat-vps")
    }

    /// Claude injects command caveats and system reminders as user turns; using
    /// one as the title would show the user machine-generated noise.
    func testInjectedCaveatsAreNotUsedAsTitles() throws {
        try writeTranscript(
            project: "-tmp-x",
            session: "cccc1111-2222-3333-4444-555566667777",
            lines: [
                userLine("<local-command-caveat>Caveat: generated by the system</local-command-caveat>"),
                userLine("the real first request"),
            ]
        )

        XCTAssertEqual(ClaudeSessionDiscovery.sessions(in: root).first?.title, "the real first request")
    }

    /// Subagent transcripts are child conversations the user cannot address.
    func testSubagentTranscriptsAreIgnored() throws {
        try writeTranscript(
            project: "-tmp-y",
            session: "dddd1111-2222-3333-4444-555566667777",
            lines: [userLine("parent session")]
        )
        try writeTranscript(
            project: "-tmp-y",
            session: "agent-9999",
            lines: [userLine("child session")],
            subdirectory: "subagents"
        )

        let sessions = ClaudeSessionDiscovery.sessions(in: root)
        XCTAssertEqual(sessions.map(\.title), ["parent session"])
    }

    func testSessionsAreSortedMostRecentFirstAndLimited() throws {
        for index in 0..<5 {
            let url = try writeTranscript(
                project: "-tmp-z",
                session: "eeee\(index)111-2222-3333-4444-555566667777",
                lines: [userLine("session \(index)")]
            )
            try FileManager.default.setAttributes(
                [.modificationDate: Date(timeIntervalSince1970: 1_000 + Double(index) * 60)],
                ofItemAtPath: url.path
            )
        }

        let sessions = ClaudeSessionDiscovery.sessions(in: root, limit: 3)
        XCTAssertEqual(sessions.map(\.title), ["session 4", "session 3", "session 2"])
    }

    func testMissingDirectoryYieldsNoSessionsRatherThanFailing() {
        let absent = root.appending(path: "does-not-exist", directoryHint: .isDirectory)
        XCTAssertTrue(ClaudeSessionDiscovery.sessions(in: absent).isEmpty)
    }

    /// Two sessions from different agents must never collide in config.toml.
    func testSuggestedTargetIDIsNamespacedByAgent() {
        let shared = "aaaa1111-2222"
        let claude = AgentSessionSummary(id: shared, agent: .claude, title: "t", lastActiveAt: .now)
        let codex = AgentSessionSummary(id: shared, agent: .codex, title: "t", lastActiveAt: .now)
        XCTAssertNotEqual(claude.suggestedTargetID, codex.suggestedTargetID)
    }
}
